[tools]

"claude" = "latest"
"npm:@fission-ai/openspec" = "latest"
"uv" = "latest"
"python" = "latest"
"ruby" = "latest"

[bootstrap.packages]
"apt:curl" = "latest"
"apt:jq" = "latest"
"brew:curl" = "latest"
"brew:jq" = "latest"
